<?php /* @var $this Zend\View\Renderer\PhpRenderer */

use Zend\Json\Json;

$applicationConfig = [
    'homeUrl' => $this->url('home', [], ['force_canonical' => true]),
    'googleAnalytics' => $this->layout()->google_analytics,
];

echo $this->inlineScript()
        ->prependScript('app = new Application('. Json::encode($applicationConfig) .');')
        ->prependFile($this->basePath('js/frontend-scripts.js?').$this->layout()->cache_bust_index).PHP_EOL;
