<?php
/* @var $this Zend\View\Renderer\PhpRenderer  */

use Zend\Json\Json;

if ($this->layout()->terminate()) {
    echo $this->content;

    return;
}

if (! $this->title) {
    $this->title = 'MySkeleton Application';
}

// some meta defaults
$this->headMeta()
     ->setName('keywords', '')
     ->setName('description', '')
     ->setName('viewport', 'width=device-width, initial-scale=1.0')
     ->setCharset('utf-8');

// common css
$this->headLink()->prependStylesheet($this->basePath('application/css/main.css?').$this->cache_bust_index, 'all');

// base javascript needed in the header, i.e. modernizr and yepnope
$this->headScript()->prependFile($this->basePath('application/js/header.js?').$this->cache_bust_index);

if ($this->error) {
    $this->bodyClass .= ' error';
}

?>
<?= $this->doctype().PHP_EOL ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="<?= $this->lang ?>"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie10 lt-ie9 lt-ie8" lang="<?= $this->lang ?>"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9" lang="<?= $this->lang ?>"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10" lang="<?= $this->lang ?>"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="<?= $this->lang ?>"> <!--<![endif]-->
<head>
    <?= $this->headTitle($this->title)->setSeparator(' | ').PHP_EOL ?>
    <?= $this->headMeta().PHP_EOL; ?>
    <?= $this->headLink().PHP_EOL ?>
    <?= $this->headScript().PHP_EOL ?>
</head>

<body class="default-layout <?= $this->escapeHtmlAttr($this->bodyClass) ?>">

    <a id="top"></a>

    <!--[if lt IE 9]>
    <div class="browsehappy">
        <p class="warning"><?= $this->translate('You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.'); ?></p>
        <div class="spacer"></div>
    </div>
    <![endif]-->

    <?php if (! $this->error) : ?>

        <?= $this->content ?>

    <?php else: // wrap error template ?>

        <div class="container padding-top-75 padding-bottom-75">
            <?= $this->content ?>
        </div>

    <?php endif;

    $applicationConfig = [
        'homeUrl' => $this->url('home', [], ['force_canonical' => true]),
        'googleAnalytics' => $this->google_analytics,
    ];

    echo $this->inlineScript()
            ->prependScript('application = new Application('. Json::encode($applicationConfig) .');')
            ->prependFile($this->basePath('application/js/scripts.js?').$this->cache_bust_index).PHP_EOL;

    ?>

</body>
</html>
