<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Controller\DevelopmentModeController' => __DIR__ . '/src/Application/Controller/DevelopmentModeController.php',
  'Application\Controller\IndexController'           => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Module'                               => __DIR__ . '/src/Application/Module.php',
  'Application\View\RenderListener'                  => __DIR__ . '/src/Application/View/RenderListener.php',
);
