<?php /* @var $this Zend\View\Renderer\PhpRenderer */

use Zend\Json\Json;

// common javascript to be loaded at the bottom of the DOM
$applicationJsPath = $this->basePath('js/application.js?' . $this->layout()->cache_bust_index);

$applicationConfig = [
    'homeUrl' => $this->url('home', [], ['force_canonical' => true]),
    'googleAnalytics' => $this->layout()->google_analytics,
];

echo $this->inlineScript()
        ->prependScript('application = new Application('. Json::encode($applicationConfig) .');')
        ->prependFile($applicationJsPath).PHP_EOL;
