<?php
/* @var $this Zend\View\Renderer\PhpRenderer  */

if ($this->layout()->terminate()) {
    echo $this->content;

    return;
}

// meta tags
foreach ($this->layout()->metas as $key => $value) {
    $this->headMeta()->appendName($key, $value);
}

// Facebook opengraph metas
foreach ($this->layout()->open_graph as $key => $value) {
    $this->headMeta()->setProperty($key, $value);
}

// common css
$this->headLink()->prependStylesheet($this->basePath('/css/main.css?'.$this->layout()->cache_bust_index), 'all');

// these is the only scripts needed in the head
// any other script is included in at the bottom of the DOM, inside 'javascript.phtml'
$this->headScript()
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js')
    ->prependFile('//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js');


$bodyClass = (isset($this->error) ? 'error' : $this->layout()->bodyClass);

?>
<?= $this->doctype().PHP_EOL ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="<?= $this->layout()->lang ?>"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie10 lt-ie9 lt-ie8" lang="<?= $this->layout()->lang ?>"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9" lang="<?= $this->layout()->lang ?>"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10" lang="<?= $this->layout()->lang ?>"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="<?= $this->layout()->lang ?>"> <!--<![endif]-->
<head>
    <?= $this->headTitle($this->layout()->title)->setSeparator(' | ').PHP_EOL ?>
    <?= $this->headMeta()->setCharset('utf-8').PHP_EOL; ?>
    <?= $this->headLink().PHP_EOL ?>
    <?= $this->headScript().PHP_EOL ?>
</head>

<body class="<?= $this->escapeHtmlAttr($bodyClass) ?>">

    <a id="top"></a>

    <!--[if lt IE 9]>
    <div class="browsehappy">
        <p class="warning"><?= $this->translate('You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.'); ?></p>
        <div class="spacer"></div>
    </div>
    <![endif]-->

    <?php if (!isset($this->error)) : ?>
        <?= $this->content ?>
    <?php else: ?>
        <div class="container text-center margin-top-75">
        <?= $this->content ?>
        </div>
    <?php endif; ?>

    <?= $this->render("layout/javascript") ?>

</body>
</html>
